name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Run Cypress Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run AutoTrader Test
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          spec: cypress/integration/autoTrader/autoTraderBasicTest.spec.js
