name: CI

on: workflow_call

jobs:
  build:
    name: Run Cypress Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run AutoTrader Test
        uses: cypress-io/github-action@v2
        with:
          browser: electron

      - name: Create screenshot
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-screenshot
          path: cypress/screenshots

      - name: Create artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-video
          path: cypress/videos
